name: Add mask
#on: push
on: 
  workflow_dispatch:
jobs:
  log:
    runs-on: ubuntu-latest
    env:
      TEST1: SuperSecretValue
    steps:
      - run: echo "${TEST1}"
      - run: echo "::add-mask::${TEST1}"
      - run: echo "${TEST1}"
