name: Artifacts
on: push
#on: 
#  workflow_dispatch:
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: echo "今日の日付：" >> date.txt
      - run: date >> date.txt
      - uses: actions/upload-artifact@v4
        with:
          name: uploaded
          path: date.txt
          retention-days: 2
  download:
    runs-on: ubuntu-latest
    needs: [upload]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: uploaded
          path: downloaded
      - run: cat downloaded/date.txt
#      - run: ls downloaded
