name: Sequential jobs
#on: push
on: 
  workflow_dispatch:
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "First job"
  second:
    runs-on: ubuntu-latest
    needs: [first]    # needsキーへ依存するfirstジョブのIDを指定
    steps:
      - run: sleep 10 && echo "Second job"
  third:
    runs-on: ubuntu-latest
    needs: [second]    # needsキーへ依存するsecondジョブのIDを指定
    steps:
      - run: sleep 10 && echo "Third job"
