name: SyntaxTest
on: push
jobs:
  print:
    runs-on: ubuntu-latest

#    #Variables
#    env: 
#      VARTEST1: ${{vars.VARTEST1}}
#    steps:
#      - run: echo "${VARTEST1}"

    #Literals
    steps:
      - run: printenv | grep 'LITERAL_'
      env:
        LITERAL_NULL: ${{ null }}
        LITERAL_BOOLEAN: ${{ true }}
        LITERAL_NUMBER: ${{ 1234 }}
        LITERAL_STRING: ${{ 'Hello' }}
        LITERAL_OMIT_STRING: World

