name: SyntaxTest
on: push
jobs:
  print:
    runs-on: ubuntu-latest

#    #Variables
#    env: 
#      VARTEST1: ${{vars.VARTEST1}}
#    steps:
#      - run: echo "${VARTEST1}"

    #Sercrets
    env: 
      SECTEST1: ${{secrets.SECTEST1}}
    steps:
      - run: echo "${SECTEST1}"

